name: Release
on:
  release:
    types:
      - created
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  # GitHub Actions don't support requiring jobs from another workflow, and `needs` doesn't work well with matrix,
  # so this workflow doesn't have testing included. Take care and only create releases from commits with the `check`
  # workflow passing.
  publish:
    name: Publish to PyPI
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install poetry-dynamic-versioning
        run: poetry self add poetry-dynamic-versioning@0.21.4
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
